# Generated by Django 4.2.6 on 2023-10-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_child_menu', to='menu.menu', verbose_name='Main menu')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nested_menu', to='menu.menu', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Menu',
            },
        ),
    ]
