# Generated by Django 4.2.6 on 2023-10-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_nested_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_child_menu', to='menu.menu', verbose_name='Main menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nested_menu', to='menu.menu', verbose_name='Parent'),
        ),
    ]
